[build]
base="apps/client"
publish="../../dist/apps/client"
command="yarn && yarn nx run client:build:production --skip-nx-cache"
# environment=
# processing=

[dev]
base="apps/client"
command="yarn nx run client:web:development --skip-nx-cache --excludeTaskDependencies"
targetPort=4200
autoLaunch=false

[[redirects]]
from="*"
to="/index.html"
status=200
